### ISSUE TITLE
Wyze Switch support

### ISSUE THREAD

**Issue by josephyancey** [JoshuaMulliken/ha-wyzebulb#10]
This doesn't seem to support the wyze switches. Since the API appears to be almost identical can we get switch support as well? If you aren't interested in adding it, I can tinker with it and see if I can make it work. Would you be willing to accept a PR for switches?

**Comment by JoshuaMulliken** [comment]
Yes, that would be great! I don't have any switches right now so I haven't been able to explore that yet

**Comment by josephyancey** [comment]
Please see this PR https://github.com/JoshuaMulliken/ha-wyzebulb/pull/11

I didn't want to make any substantial changes to the way you integrated with HA so as it is, if somebody has both a bulb and a switch/plug, they will have to put their login info twice and the component will hit the Wyze API twice. It only happens when the component is setup so it isn't the end of the world.

**Comment by JoshuaMulliken** [comment]
This has been merged and published in [release v0.3.0](https://github.com/JoshuaMulliken/ha-wyzebulb/releases/tag/v0.3.0)!
