### ISSUE TITLE
Status update

### ISSUE THREAD

**Issue by whwar9739** [JoshuaMulliken/ha-wyzebulb#2]
Not sure if this is even possible, but is there a way for the api to get the status of the bulb and update the component in Home Assistant? For example, if someone turns a bulb on or off using the Wyze app, could the Home Assistant component be updated to reflect that change?

**Comment by JoshuaMulliken** [comment]
It will update. I am not sure at what rate HA runs the .update() function but it will change the status eventually.

**Comment by JoshuaMulliken** [comment]
@whwar9739 I believe it may be about 30 seconds
