### ISSUE TITLE
No method to automatically update the integration

### ISSUE THREAD

**Issue by basesnow** [JoshuaMulliken/ha-wyzebulb#4]
This is my first time adding a component that doesn't show up in integrations or a custom community store like HACS. How will I know there is an update available, how do I update?

**Comment by JoshuaMulliken** [comment]
@basesnow I do not have a method for this currently. I will look into adding this to HACS or make it possible to include it in HACS

**Comment by JoshuaMulliken** [comment]
@basesnow I was able to successfully add this to HACS. I have added instructions to the [README.md](https://github.com/JoshuaMulliken/ha-wyzebulb/blob/master/README.md)

**Comment by basesnow** [comment]
Awesome, thanks!
