### ISSUE TITLE
Brightness set to 100% when you adjust the color temperature

### ISSUE THREAD

**Issue by basesnow** [JoshuaMulliken/ha-wyzebulb#9]
when I go to change the temperature in the info card, the brightness gets set to 100% every time.

**Comment by JoshuaMulliken** [comment]
I think I have fixed this in the latest release: https://github.com/JoshuaMulliken/ha-wyzebulb/releases/tag/v0.2.1

Please update and let me know if it is fixed for you.

**Comment by basesnow** [comment]
still seeing the issue. Noticed that you added debug logging in the latest release. Not sure how to exactly what I would replace "homeassistant.components.homekit" in the code below, but if you can tell me, I can set it up and run it.

`logger:
  default: warning
  logs:
    homeassistant.components.homekit: debug
    pyhap: debug`

**Comment by JoshuaMulliken** [comment]
My logger statement looks like this:
``` yaml
logger:
  default: warning
  logs:
    custom_components.wyzeapi: debug
```

**Comment by JoshuaMulliken** [comment]
Are you installing from hacs and have you rebooted? @basesnow

**Comment by JoshuaMulliken** [comment]
@basesnow if you can try [this release](https://github.com/JoshuaMulliken/ha-wyzebulb/releases/tag/v0.2.2) for me that would be great! Also if you could provide me with a description of what mechanism you are using to set the color temperature, for example with a script, automation, or the lovelace ui.

**Comment by JoshuaMulliken** [comment]
It appears to be fixed to me. I will be closing this issue now if you continue to experience the problem then please reach out again @basesnow
